<GerenciadorDeTelas>
    Menu:
        name: 'menu'
    Usuarios:
        name: 'VerTodosusuarios'
    UsuariosCadastrar:
        name: 'Cadastrarusuarios'
    Livros:
        name: 'Livrosacervo'
    Exemplares:
        name: 'Exemplaresacervo'
    LivrosCadastrar:
        name: 'CadastrarLivroacervo'
    ExemplaresCadastrar:
        name: 'CadastrarExemplaracervo'
    Reservas:
        name: 'VerTodasreservas'
    Emprestimos:
        name: 'VerTodosemprestimos'
